Header header



uint8 Nose = 0
uint8 Neck = 1
uint8 Right_Shoulder = 2
uint8 Right_Elbow = 3
uint8 Right_Wrist = 4
uint8 Left_Shoulder = 5
uint8 Left_Elbow = 6
uint8 Left_Wrist = 7
uint8 Right_Hip = 8
uint8 Right_Knee = 9
uint8 Right_Ankel = 10
uint8 Left_Hip = 11
uint8 Left_Knee = 12
uint8 Left_Ankel = 13
uint8 Left_Eye = 14
uint8 Right_Eye = 15
uint8 Left_Ear = 16
uint8 Right_Ear = 17


PointOfInterest2D[] skeleton


