# This service allows client to select humans from the human database.

# Examples:
# - query='face_id IS NOT NULL' -> returns every humans for which a face is being tracked
# - query='age >= 10 and age <= 20' -> returns humans whose age is estimated to be between 10 and 20
# - query='name = "John"' -> humans whose name is John

# This string is used as the 'WHERE' clause in the SQL query 'SELECT * FROM humans WHERE ...' run against the humans database.
# Leave empty to select all humans (ie, equivalent to what is published on the /humans topic)
string query
---
Person[] group # the list of persons matching the query
